services:
  postgres:
    image: postgres:17
    container_name: rmm_insight_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: rmm_insight
      POSTGRES_USER: rmm
      POSTGRES_PASSWORD: RMMdatto.supportcaico

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: