"""Atualiza estrutura completa do banco

Revision ID: 787f8c13695e
Revises: b302506a560a
Create Date: 2026-07-09 15:53:07.543673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787f8c13695e'
down_revision = 'b302506a560a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpoint_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tipo', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('severidade', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('data_alerta', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_alertas_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertas_severidade'), ['severidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertas_status'), ['status'], unique=False)
        batch_op.create_foreign_key(None, 'endpoints', ['endpoint_id'], ['id'])

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.create_index(batch_op.f('ix_clientes_nome'), ['nome'], unique=True)

    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tipo_dispositivo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fabricante', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('modelo', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('numero_serie', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('usuario_logado', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('endereco_ip', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('ultima_comunicacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('uptime', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('politica', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('memoria_ram', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('disco_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('disco_livre', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.create_index(batch_op.f('ix_endpoints_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_endpoints_status'), ['status'], unique=False)
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_endpoints_status'))
        batch_op.drop_index(batch_op.f('ix_endpoints_cliente_id'))
        batch_op.drop_column('criado_em')
        batch_op.drop_column('disco_livre')
        batch_op.drop_column('disco_total')
        batch_op.drop_column('memoria_ram')
        batch_op.drop_column('politica')
        batch_op.drop_column('uptime')
        batch_op.drop_column('ultima_comunicacao')
        batch_op.drop_column('status')
        batch_op.drop_column('endereco_ip')
        batch_op.drop_column('usuario_logado')
        batch_op.drop_column('numero_serie')
        batch_op.drop_column('modelo')
        batch_op.drop_column('fabricante')
        batch_op.drop_column('tipo_dispositivo')
        batch_op.drop_column('cliente_id')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_nome'))
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('observacoes')
        batch_op.drop_column('ativo')

    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_alertas_status'))
        batch_op.drop_index(batch_op.f('ix_alertas_severidade'))
        batch_op.drop_index(batch_op.f('ix_alertas_endpoint_id'))
        batch_op.alter_column('descricao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('data_alerta')
        batch_op.drop_column('status')
        batch_op.drop_column('severidade')
        batch_op.drop_column('tipo')
        batch_op.drop_column('endpoint_id')

    # ### end Alembic commands ###
